# name: CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Use Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18
#       - name: Install dependencies (use npm ci when lockfile exists)
#         run: |
#           if [ -f package-lock.json ]; then
#             echo "package-lock.json found — using npm ci"
#             npm ci
#           else
#             echo "package-lock.json not found — running npm install (will generate lockfile)"
#             npm install
#           fi
#       - name: Build
#         run: npm run build
#       - name: Run unit tests
#         run: npm test
#       - name: Run Cypress (headless)
#         run: npm run cypress:run